version: '3'

services:
  orangehrm:
    image: orangehrm/orangehrm
    ports:
      - 80:80
      - 3306:3306
    environment:
      MYSQL_DATABASE: orangehrm
      MYSQL_USER: orangehrm
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: orangehrm
      MYSQL_USER: orangehrm
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - orangehrm-db:/var/lib/mysql

volumes:
  orangehrm-db:
