version: '3'
<<<<<<< HEAD
=======

>>>>>>> cdcbf7dda9c532205917c1e094385c22ae019580
services:
  orangehrm:
    image: orangehrm/orangehrm
    ports:
      - 80:80
    environment:
      MYSQL_DATABASE: orangehrm
      MYSQL_USER: orangehrm
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: orangehrm
      MYSQL_USER: orangehrm
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
<<<<<<< HEAD
      - orangehrm-db2:/var/lib/mysql

volumes:
  orangehrm-db2:
=======
      - orangehrm-db:/var/lib/mysql

volumes:
  orangehrm-db:
>>>>>>> cdcbf7dda9c532205917c1e094385c22ae019580
